env = "Testnet" # SideSwap testnet server (Liquid Testnet network)
#env = "Prod" # SideSwap prod server (Liquid network)

# The dir for storing work files. The contents must be preserved.
work_dir = "/home/user/sideswap_manager/work_dir"

mnemonic = "<YOUR_MNEMONIC>"
script_variant = "wpkh" # Use "shwpkh" for nested segwit addresses

[ws_server]
listen_on = "127.0.0.1:3102"

# An optional list of additional whitelisted assets
whitelisted_assets = [
    #"78557eb89ea8439dc1a519f4eb0267c86b261068648a0f84a5c6b55ca39b66f1", # B-JDE (Liquid only)
    #"649f01bd72fbe33a70508e752044a2b0f91cf73612b70e03f337d095daa8b002", # PXTST (Testnet only)
]

# Optional affiliate key
# affiliate_api_key = "<YOUR_API_KEY>"
