[package]
name = "sideswap_types"
version = "0.1.2"
edition = "2024"

[dependencies]
elements.workspace = true
hex.workspace = true
serde_bytes.workspace = true
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true
